### ISSUE TITLE
Multiple block devices

### ISSUE THREAD

**Issue by pcwrt** [dguerri/LibVirtKvm-scripts#11]
First:  awesome script ... thanks for writing this!

For both backups and consolidation the script breaks the list of block_devices returned from "virsh domblklist" into block_device using:
for block_device in "$block_devices"; do
"for" will treat "$block_devices" (in quotes) as a single argument and assign all of the block devices to $block_device.  I think what you meant was (no quotes):
    for block_device in $block_devices; do

For example (with quotes):
    # for i in "a b c"; do printf "arg: $i\n"; done
Returns:
    "arg: a b c"

Where (without quotes):
    # for i in a b c; do printf "arg: $i\n"; done
Returns:
    arg: a
    arg: b
    arg: c

**Comment by dguerri** [comment]
Thanks @pcwrt .
That is definitely a bug. Go ahead and fix it, if you feel like.
Or I will look into it later if you want.

**Comment by dguerri** [comment]
Same as #12.
