### ISSUE TITLE
a different KVM path is needed for CentOS 7

### ISSUE THREAD

**Issue by svorobyov** [dguerri/LibVirtKvm-scripts#13]
In CentOS 7 a different path is seemingly needed for the KVM variable, because:

[root@dualix /]# find / -type f -name "kvm" 
...none found...
[root@dualix /]# find / -type f -name "qemu-kvm" 
/usr/libexec/qemu-kvm

Therefore, the following add-on (after # Add this...) can help:

\# Executables
QEMU_IMG="/usr/bin/qemu-img"
VIRSH="/usr/bin/virsh"
KVM="/usr/bin/kvm"
if [ -x "/usr/bin/qemu-kvm" ]; then
KVM="/usr/bin/qemu-kvm"
fi
\# Add this! (SV, for CentOS 7)
if [ -x "/usr/libexec/qemu-kvm" ]; then
KVM="/usr/libexec/qemu-kvm"
fi

On my system:

[root@dualix /]# grep -i centos /etc/*
/etc/redhat-release:CentOS Linux release 7.1.1503 (Core)
/etc/system-release:CentOS Linux release 7.1.1503 (Core)

After this addition the fi-backup.sh script works on my CentOS 7. Maybe a case analysis, system-by-system is required?

**Comment by dguerri** [comment]
In order to create some CI tests on travis, I want to use qemu (not KVM). Specifically: `qemu-system-x86_64`

Where is installed `qemu-system-x86_64` on centos?

**Comment by svorobyov** [comment]
[root@dualix sv]# find / -type f -name "qemu-system-x86_64"         
/usr/bin/qemu-system-x86_64

**Comment by dguerri** [comment]
Thanks :)

**Comment by dguerri** [comment]
Fixed. Fix merged in master.
