### ISSUE TITLE
check_version fails

### ISSUE THREAD

**Issue by markus9999** [dguerri/LibVirtKvm-scripts#16]
Hello,

i currently test this script first issue

[ERR] Unsupported libVirt version '1.2.9'. Please use libVirt 0.9.13 or greather

HTH

regards max

**Comment by dguerri** [comment]
That could be not supported.
I don't have the latest libVirt version handy, could you please remove that check and paste here the output of `fi-backup.sh` with `-d`?

**Comment by markus9999** [comment]
-->
[DEB] /usr/bin/qemu-img version '2.1.3' is supported
[DEB] QEMU/KVM version '2.1.3,' is supported
[ERR] <domain name> is missing!
   fi-backup version 2.0.0 - by Davide Guerri <davide.guerri@gmail.com>

   Usage:

   ./fi-backup.sh [-c|-C] [-q] [-h] [-d] [-v] [-V] [-b <directory>] <domain name>|all

   Options
      -b <directory>    Copy previous snapshot/base image to the specified <directory>
      -c                Consolidation only
      -C                Snapshot and consolidation
      -q                Use quiescence (qemu agent must be installed in the domain)
      -d                Debug
      -h                Print usage and exit
      -v                Verbose
      -V                Print version and exit
<--

at the moment i've changed the required version from 0.9.13 to 1.0.0 that works fine

**Comment by dguerri** [comment]
yep, thanks.
Can you try also to perform a backup, please?

**Comment by dguerri** [comment]
mmh `[ERR] is missing!` is not good.

**Comment by markus9999** [comment]
ok, in a few minutes, i must copy some files

**Comment by dguerri** [comment]
@mamoit backup your stuff first! I have no idea about what is going to happen with that libvirt version :)

**Comment by markus9999** [comment]
ok here it is

[DEB] /usr/bin/qemu-img version '2.1.3' is supported
[DEB] QEMU/KVM version '2.1.3,' is supported
[DEB] Snapshot for domain 'vhs-www1' requested
[DEB] Using timestamp '20150609-160931'
[DEB] Snapshotting block devices for 'vhs-www1' using suffix 'bimg-20150609-160931'
[VER] Snapshot for block devices of 'vhs-www1' successful
[VER] Copy backing file '/var/lib/libvirt/images/debianwheezy.bimg-20150609-154341' to '/backup/debianwheezy.bimg-20150609-154341'
[DEB] Parent backing file: '/var/lib/libvirt/images/debianwheezy.bimg-20150609-120145'

**Comment by dguerri** [comment]
thanks @markus9999
It seems to work but I want to be sure :)
Please add the `-d`, post the output here. Then try (again with `-d`) try to consolidate, please (`-c`)

**Comment by markus9999** [comment]
ok, first one

-->
ccron-vhs:/usr/local/sbin # /usr/local/sbin/fi-backup.sh -b /backup -d vhs-www1
[DEB] libVirt version '1.2.9' is supported
[DEB] /usr/bin/qemu-img version '2.1.3' is supported
[DEB] QEMU/KVM version '2.1.3,' is supported
[DEB] Snapshot for domain 'vhs-www1' requested
[DEB] Using timestamp '20150609-204433'
[DEB] Snapshotting block devices for 'vhs-www1' using suffix 'bimg-20150609-204433'
[VER] Snapshot for block devices of 'vhs-www1' successful
[VER] Copy backing file '/var/lib/libvirt/images/debianwheezy.bimg-20150609-160931' to '/backup/debianwheezy.bimg-20150609-160931'
[DEB] Parent backing file: '/var/lib/libvirt/images/debianwheezy.bimg-20150609-154341'

<--

**Comment by markus9999** [comment]
next

ccron-vhs:/usr/local/sbin # /usr/local/sbin/fi-backup.sh -c -d vhs-www1
[DEB] libVirt version '1.2.9' is supported
[DEB] /usr/bin/qemu-img version '2.1.3' is supported
[DEB] QEMU/KVM version '2.1.3,' is supported
[DEB] Consolidation of block devices for 'vhs-www1' requested
[DEB] Block devices to be consolidated:
        /var/lib/libvirt/images/debianwheezy.bimg-20150609-204433
[DEB] Consolidation of block device: '/var/lib/libvirt/images/debianwheezy.bimg-20150609-204433' for 'vhs-www1'
[DEB] Parent block device: '/var/lib/libvirt/images/debianwheezy.bimg-20150609-160931'
[VER] Consolidation of block device '/var/lib/libvirt/images/debianwheezy.bimg-20150609-204433' for 'vhs-www1' successful
[VER] Deleting old backup files for 'vhs-www1'
[DEB] Processing old backing file '/var/lib/libvirt/images/debianwheezy.bimg-20150609-160931' for 'vhs-www1'
[DEB] Parent backing file: '/var/lib/libvirt/images/debianwheezy.bimg-20150609-154341'
[VER] Deleting backing file '/var/lib/libvirt/images/debianwheezy.bimg-20150609-160931'
[DEB] Next file in backing file chain: '/var/lib/libvirt/images/debianwheezy.bimg-20150609-154341'
[DEB] Processing old backing file '/var/lib/libvirt/images/debianwheezy.bimg-20150609-154341' for 'vhs-www1'
[DEB] Parent backing file: '/var/lib/libvirt/images/debianwheezy.bimg-20150609-120145'
[VER] Deleting backing file '/var/lib/libvirt/images/debianwheezy.bimg-20150609-154341'
[DEB] Next file in backing file chain: '/var/lib/libvirt/images/debianwheezy.bimg-20150609-120145'
[DEB] Processing old backing file '/var/lib/libvirt/images/debianwheezy.bimg-20150609-120145' for 'vhs-www1'
[DEB] Parent backing file: '/var/lib/libvirt/images/debianwheezy.bimg-20150609-111106'
[VER] Deleting backing file '/var/lib/libvirt/images/debianwheezy.bimg-20150609-120145'
[DEB] Next file in backing file chain: '/var/lib/libvirt/images/debianwheezy.bimg-20150609-111106'
[DEB] Processing old backing file '/var/lib/libvirt/images/debianwheezy.bimg-20150609-111106' for 'vhs-www1'
[DEB] Parent backing file: '/var/lib/libvirt/images/debianwheezy.bimg-20150609-104805'
[VER] Deleting backing file '/var/lib/libvirt/images/debianwheezy.bimg-20150609-111106'
[DEB] Next file in backing file chain: '/var/lib/libvirt/images/debianwheezy.bimg-20150609-104805'
[DEB] Processing old backing file '/var/lib/libvirt/images/debianwheezy.bimg-20150609-104805' for 'vhs-www1'
[DEB] Parent backing file: ''
[VER] Deleting backing file '/var/lib/libvirt/images/debianwheezy.bimg-20150609-104805'
[DEB] Next file in backing file chain: ''

**Comment by dguerri** [comment]
Ok thanks @markus9999 . I will submit a patch shortly for your issue!

**Comment by dguerri** [comment]
Weird. Just using a "static" version, in the piece of code that performs that check, I can' t reproduce it.
(I have just replaced `print_v` with `echo`)
    (davide:murray)-[0]-(~/D/LibVirtKvm-scripts) # function check_version()
    > {
    >     local version=$1 check=$2
    >     local winner=$(echo -e "$version\n$check" | sed '/^$/d' | sort -nr | \
    >       head -1)
    >     [[ "$winner" = "$version" ]] && return 0
    >     return 1
    > }
    (davide:murray)-[0]-(~/D/LibVirtKvm-scripts) # 
    (davide:murray)-[0]-(~/D/LibVirtKvm-scripts) # version='1.2.9'
    (davide:murray)-[0]-(~/D/LibVirtKvm-scripts) # if check_version "$version" '0.9.13'; then
    >   echo "libVirt version '$version' is supported"
    > else
    >   echo "Unsupported libVirt version '$version'. Please use libVirt 0.9.13 or greather"
    >   _ret=2
    > fi
    libVirt version '1.2.9' is supported
    (davide:murray)-[0]-(~/D/LibVirtKvm-scripts) # 

@markus9999 can you please paste the output of the following command:

    /usr/bin/virsh -v

**Comment by markus9999** [comment]
sory for late answer, here it is

-->
ccron-vhs:/usr/local/sbin # virsh -v
1.2.9
<--

**Comment by markus9999** [comment]
so

**Comment by markus9999** [comment]
Ok, I've found a solution, Coudl you test this ?

replace 

local winner=$(echo -e "$version\n$check" | sed '/^$/d' | sort -nr |  head -1)

by 

local winner=$(echo -e "$version\n$check" | sed '/^$/d' | sort -Vr |  head -1)

I dont know if all currently used versions of sort support the -V option

but this works for me, maybe for others to

regards

**Comment by dguerri** [comment]
That's interesting. I will try it asap.
-V is a GNU extension, so it should bey present on (recent) Linux boxes.
Anyhow, I don't get why the numeric sort doesn't work for your case. I have quickly tested that code on OsX, but I guess -n in Linux would do something different.

Which operating system are you using?

**Comment by markus9999** [comment]
I use openSUSE already for many years, 13.2 is the latest.

**Comment by dguerri** [comment]
Thanks @markus9999 . I am fixing your issue now.

**Comment by markus9999** [comment]
Thx a lot for your support ;)

**Comment by dguerri** [comment]
Thank you for reporting the issue.
I am closing it now. Feel free to reopen it or open a new one if needed.
