### ISSUE TITLE
Any plans for using active blockcommit?

### ISSUE THREAD

**Issue by xr09** [dguerri/LibVirtKvm-scripts#20]
Any plans for using the latest features of libvirt? This method is way faster than the current one.

http://wiki.libvirt.org/page/Live-disk-backup-with-active-blockcommit

**Comment by dguerri** [comment]
Hi @xr09, sorry for the delayed reply.
Well, I am always open to trying new stuff :) 
I am a bit rusty on this, can you please tell me what improvement we will get using blockcommit?

Thank!

**Comment by xr09** [comment]
I'm no libvirt expert, can't comment any low level details, but tried this approach manually, is way more efficient.
In brief, it performs the backup as if were a snapshot, by freezing the disk and using a new tmp disk so you can get in and copy the original disk, then it "pivots" (merges back changes to the original image) in a heartbeat compared to the old method, really fast.

Maybe I'm using your script the wrong way but the pivoting part was really slow for me. I'd appreciate if you tested this relatively new method. 

I'm running a test server with Debian8/libvirt, loving the results so far, the only weak point is backups, hope this script will fill the void. Thanks for good work.

**Comment by dguerri** [comment]
Thanks. I will take a look asap :+1:

**Comment by franklouwers** [comment]
Hi Davide,

would this be an interesting approach for you? Do you plan on implementing it? Would like to contribute if that helps...

**Comment by dguerri** [comment]
@franklouwers I think that would be a great enhancement. I just haven't found the time to dig into it.
Please feel free to submit a PR with a quick test (.travis.yml) and add yourself to a credit file!  ;)

**Comment by dguerri** [comment]
@franklouwers @xr09 I added experimental support to blockcommit in this branch https://github.com/dguerri/LibVirtKvm-scripts/tree/features/blockcommit
It is very basic and the backing files handling could be probably improved wrt the blockpull method... nevertheless I'd like to keep backward compatibility for older ubuntu distos...

Can you please give it a go and let me know if it works for you?

**Comment by dguerri** [comment]
@franklouwers @xr09 is the blockcommit branch working for you?

**Comment by xr09** [comment]
@dguerri It seems to work flawlessly.

These are the steps I followed to test it, correct me if I missed anything:

Disk size: 2.4 Gb

First, made a full backup

```shell
    ./fi-backup.sh -v -b /srv/fib/sn  debian-core
    [INF] libVirt version '1.2.9' support is experimental
    [VER] Snapshot for block devices of 'debian-core' successful
    [VER] Copy backing file '/srv/virt/debian_core.qcow2' to '/srv/fib/sn/debian_core.qcow2'
    [VER] No parent backing file for '/srv/virt/debian_core.qcow2'
```

This made a snapshot, froze the image and copied it to the destination folder. (1m7.905s)

Then, several other snapshots

```shell
    ./fi-backup.sh -v -b /srv/fib/sn  debian-core
    [INF] libVirt version '1.2.9' support is experimental
    [VER] Snapshot for block devices of 'debian-core' successful
    [VER] Copy backing file '/srv/virt/debian_core.bimg-20151113-145753' to '/srv/fi/sn/debian_core.bimg-20151113-145753'```
```

These snapshots took less than 0.3s on average


Consolidation:

```shell
./fi-backup.sh -v -c  debian-core
[INF] libVirt version '1.2.9' support is experimental
[VER] Consolidation of block device '/srv/virt/debian_core.bimg-20151113-150025' for 'debian-core' successful
[VER] Deleting old backup files for 'debian-core'
[VER] Deleting backing file '/srv/virt/debian_core.bimg-20151113-150025'
[VER] Deleting backing file '/srv/virt/debian_core.bimg-20151113-150023'
[VER] Deleting backing file '/srv/virt/debian_core.bimg-20151113-150022'
[VER] Deleting backing file '/srv/virt/debian_core.bimg-20151113-145805'
[VER] Deleting backing file '/srv/virt/debian_core.bimg-20151113-145753'
[VER] Deleting backing file '/srv/virt/debian_core.bimg-20151113-145750'
[VER] Deleting backing file '/srv/virt/debian_core.bimg-20151113-145638'
[INF] '/srv/virt/debian_core.qcow2' doesn't seem to be a backup backing file image.
[INF] Stopping backing file chain removal
```

Time elapsed: 0m0.355s  :+1:

**Comment by dguerri** [comment]
per #27 I am closing this feature request.
Don't forget to say "thank you" to @AJRepo ;)

Cheers!
