### ISSUE TITLE
TravisCI tests and KVM/libvertd  seem incompatible

### ISSUE THREAD

**Issue by AJRepo** [dguerri/LibVirtKvm-scripts#32]
I've been trying to get the latest builds to work with TravisCI and also with Docker [in a scratch branch](https://github.com/AJRepo/LibVirtKvm-scripts/tree/travistests). Docker attempts [failed too](https://github.com/docker/hub-feedback/issues/1055). 

I can run tests locally and they run fine, but there seems to be a block at the TravisCI and hub.Docker.com blocking containerized libvirtd which is needed to automate the backup tests.  

Suggestions?

**Comment by AJRepo** [comment]
Fixed with commit 9fc26053a34833fb61cdd00543b6f72b9aa38a32

**Comment by cherusk** [comment]
Downgrading to xenial also worked, definetly something with bionic.
