### ISSUE TITLE
XML dumps

### ISSUE THREAD

**Issue by ASAPHAANING** [dguerri/LibVirtKvm-scripts#36]
I read the nuts & bolts as well as the README and nowhere is it mentioned that the newer commits still include a backup of the libvirt XML definitions. Am I parsing the arguments wrong or is that functionality no longer present?

**Comment by AJRepo** [comment]
I don't believe any functionality was removed. 

Are you referring to the -s flag for dump state/status? 

That's still in there.

**Comment by ASAPHAANING** [comment]
In previous revisions no argument was required for every backup to include an xml dump for the composition of the domain. When I've replaced my old with the new script I will return here to conclude whether this is what I was referring to.

**Comment by ASAPHAANING** [comment]
I just switched to the new version now realized that state dump is not producing what I expected. Previously, the script would generate an xml dump used to describe the right configuration when creating a VM host along with the backed up copy of the disk image. Is this feature missing or am I not finding it right? Should I instead use this state dump to accomplish the same- in that case, how so?

Before, when restoring a libvirt guest you could simply go to your CLI and run:
sudo virsh define XXX.xml

**Comment by AJRepo** [comment]
I did a search through past git commits and found no mention of 'xml'

The only dump state feature to have ever existed requires specifying the output directory. 

`-s, --dump_state_dir <directory>  Dump domain status in the specified directory`

And creates a .gz file as described [on the KVM Migration page](https://www.linux-kvm.org/page/Migration)

I think you are confused between this program fi-backup which _calls_ virsh and the program virsh itself. 

I believe you are thinking of "virsh dumpxml DOMAIN > FOO.xml"

**Comment by ASAPHAANING** [comment]
You're right! I mistook it for [another authors script](https://gist.github.com/cabal95/e36c06e716d3328b512b) which I am using currently.

This script produces the dumpxml from virsh :)
